name: Sync to GitFlic

on:
  push:
    branches: [ "main" ]   # или "master", если основная ветка так называется
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Mirror"
          git config --global user.email "mirror@github.com"

      - name: Push to GitFlic
        env:
          GITFLIC_TOKEN: ${{ secrets.GITFLIC_TOKEN }}
        run: |
          GITFLIC_REPO="https://oauth2:${GITFLIC_TOKEN}@gitflic.ru/project/vocxod235/c08a.git"
          git remote add gitflic $GITFLIC_REPO
          git push --mirror --force gitflic
